---
name: Lock

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write

jobs:
  lock:
    name: ðŸ”’ Lock closed issues and PRs
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          process-only: "issues, prs"
          issue-inactive-days: "30"
          issue-lock-reason: ""
          pr-inactive-days: "1"
          pr-lock-reason: ""
